import React from "react";
import Head from "next/head";
function Contrbute() {
  return (
    <div>
      <Head>
        <title>Contribute</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <iframe
        className="bg-transparent border border-gray-300"
        src="https://airtable.com/embed/appTeV1ALbXz6aYeh/shr1VcbYiviLcjtsl?backgroundColor=pink"
        frameborder="0"
        onmousewheel=""
        width="100%"
        height="1000px"
      ></iframe>
    </div>
  );
}

export default Contrbute;
